// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Cadence",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Cadence",
            targets: ["AppModule"],
            bundleIdentifier: "com.dhirajbodake.Cadence",
            teamIdentifier: "PUMDFHHYD3",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "Cadence needs microphone access to analyze your speech volume and pacing in real-time."),
                .speechRecognition(purposeString: "Cadence uses speech recognition locally to track filler words and calculate your words-per-minute."),
                .camera(purposeString: "Cadence uses the camera entirely on-device to analyze your eye contact.")
            ],
            appCategory: .productivity
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.v5]
)
